// <auto-generated />
using System;
using Longa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Longa.Infrastructure.Migrations
{
    [DbContext(typeof(LongaDbContext))]
    partial class LongaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Longa.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_trip_id");

                    b.Property<Guid>("RiderTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_trip_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("DriverTripId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_driver_trip_id");

                    b.HasIndex("RiderTripId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_rider_trip_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Longa.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_keys_created_at");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Longa.Domain.Entities.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_tokens");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_push_tokens_user_id");

                    b.ToTable("push_tokens", (string)null);
                });

            modelBuilder.Entity("Longa.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_address");

                    b.Property<decimal>("DestinationLat")
                        .HasColumnType("numeric")
                        .HasColumnName("destination_lat");

                    b.Property<decimal>("DestinationLng")
                        .HasColumnType("numeric")
                        .HasColumnName("destination_lng");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<decimal>("PickupLat")
                        .HasColumnType("numeric")
                        .HasColumnName("pickup_lat");

                    b.Property<decimal>("PickupLng")
                        .HasColumnType("numeric")
                        .HasColumnName("pickup_lng");

                    b.Property<string>("PriceDisplay")
                        .HasColumnType("text")
                        .HasColumnName("price_display");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("DepartureAt")
                        .HasDatabaseName("ix_trips_departure_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trips_user_id");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("ix_trips_role_status");

                    b.ToTable("trips", null, t =>
                        {
                            t.HasCheckConstraint("driver_price_display_check", "((role = 'driver' AND price_display IS NOT NULL AND price_display != '') OR (role = 'rider'))");
                        });
                });

            modelBuilder.Entity("Longa.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth0user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceMake")
                        .HasColumnType("text")
                        .HasColumnName("device_make");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentifierForVendor")
                        .HasColumnType("text")
                        .HasColumnName("identifier_for_vendor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0user_id");

                    b.HasIndex("IdentifierForVendor")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identifier_for_vendor");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Longa.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Longa.Domain.Entities.Trip", "DriverTrip")
                        .WithOne("BookingAsDriver")
                        .HasForeignKey("Longa.Domain.Entities.Booking", "DriverTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trips_driver_trip_id");

                    b.HasOne("Longa.Domain.Entities.Trip", "RiderTrip")
                        .WithOne("BookingAsRider")
                        .HasForeignKey("Longa.Domain.Entities.Booking", "RiderTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trips_rider_trip_id");

                    b.Navigation("DriverTrip");

                    b.Navigation("RiderTrip");
                });

            modelBuilder.Entity("Longa.Domain.Entities.PushToken", b =>
                {
                    b.HasOne("Longa.Domain.Entities.User", "User")
                        .WithOne("PushToken")
                        .HasForeignKey("Longa.Domain.Entities.PushToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Longa.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Longa.Domain.Entities.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trips_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Longa.Domain.Entities.Trip", b =>
                {
                    b.Navigation("BookingAsDriver");

                    b.Navigation("BookingAsRider");
                });

            modelBuilder.Entity("Longa.Domain.Entities.User", b =>
                {
                    b.Navigation("PushToken");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
